branch check

diff --git a/{{cookiecutter.repo}}/.github/workflows/prod_pr.yml b/{{cookiecutter.repo}}/.github/workflows/prod_pr.yml
--- a/{{cookiecutter.repo}}/.github/workflows/prod_pr.yml
+++ b/{{cookiecutter.repo}}/.github/workflows/prod_pr.yml
@@ -22,6 +22,12 @@ jobs:
       contents: write
 
     steps:
+      - name: Check merge branch
+        if: github.head_ref != 'master'
+        run: |
+          echo "ERROR: Only master may be merged into prod" && \
+          exit 1
+
       - name: Clone repo
         uses: actions/checkout@v4
         with:
