prod

diff --git a/{{cookiecutter.repo}}/.github/workflows/prod.yml b/{{cookiecutter.repo}}/.github/workflows/prod.yml
--- a/{{cookiecutter.repo}}/.github/workflows/prod.yml
+++ b/{{cookiecutter.repo}}/.github/workflows/prod.yml
@@ -1,10 +1,4 @@
-{%- set cc = cookiecutter -%}
 {%- raw -%}
-# Please ensure the following GitHub repository action secrets are set up:
-#  - DOCKER_REGISTRY_USER
-#  - DOCKER_REGISTRY_PASSWORD
-#  - PYPI_ACCESS_TOKEN
-
 name: Prod
 run-name: "${{ github.event.head_commit.message }} | ${{ github.actor }}"
 
@@ -13,13 +7,8 @@ on:
     branches: [ prod ]
 
 env:
-  repo: "${{ github.event.repository.name }}"
   cli: "bin/${{ github.event.repository.name }}"
-{%- endraw %}
-  org: "{{ cc.git_organization }}"
-  org_url: "{{ cc.organization_url }}"
-  docker_registry: "{{ cc.docker_registry }}"
-{%- raw %}
+  GH_TOKEN: "${{ secrets.GH_TOKEN }}"
 
 jobs:
   prod:
@@ -30,19 +19,14 @@ jobs:
     steps:
       - name: Clone repo
         uses: actions/checkout@v4
-
-      - name: Change repo permissions
-        run: chmod -R o+w ../
-
-      - name: Docker login
-        uses: docker/login-action@v3
         with:
-          registry: ${{ env.docker_registry }}
-          username: ${{ secrets.DOCKER_REGISTRY_USER }}
-          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
+          token: ${{ secrets.GH_TOKEN }}
+
+      - name: Setup
+        uses: ./.github/actions/setup
 
       - name: Pull image
-        run: $($cli docker-pull-dev) || echo "docker image not found"
+        run: $cli docker-pull-dev || echo "docker image not found"
 
       - name: Build image
         run: $cli docker-build-from-cache
